import os

def build_markdown_report(records):
    """
    Membuat tabel markdown dari data rekap mahasiswa.
    """
    header = "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |\n"
    header += "|---|---|---:|---:|:---:|\n"
    rows = ""
    for r in records:
        rows += f"| {r['NIM']} | {r['Nama']} | {r['Hadir (%)']:.1f} | {r['Nilai Akhir']:.2f} | {r['Predikat']} |\n"
    return f"# Rekap Nilai Mahasiswa\n\n{header}{rows}\nGenerated by student_performance_tracker"


def build_html_report(records):
    """Membuat tabel HTML dengan warna berdasarkan predikat"""
    color_map = {
        "A": "#c8e6c9",  # hijau muda
        "B": "#bbdefb",  # biru muda
        "C": "#fff9c4",  # kuning
        "D": "#ffe0b2",  # oranye
        "E": "#ffcdd2",  # merah mudass
    }
    html = """
<html>
<head>
<meta charset='utf-8'>
<title>Rekap Nilai Mahasiswa</title>
<style>
body { background-color: #111; color: white; }
table { border-collapse: collapse; width: 70%; margin: 20px auto; font-family: sans-serif; }
th, td { border: 1px solid #999; padding: 8px; text-align: center; }
th { background-color: #222; }
caption { font-size: 1.4em; margin-bottom: 10px; color: white; }
</style>
</head>
<body>
<table>
<caption>Rekap Nilai Mahasiswa</caption>
<tr><th>NIM</th><th>Nama</th><th>Hadir (%)</th><th>Nilai Akhir</th><th>Predikat</th></tr>
"""
    for r in records:
        warna = color_map.get(r["Predikat"], "#fff")
        html += f"<tr style='background-color:{warna}'><td>{r['NIM']}</td><td>{r['Nama']}</td><td>{r['Hadir (%)']:.1f}</td><td>{r['Nilai Akhir']:.2f}</td><td>{r['Predikat']}</td></tr>\n"
    html += "</table>\n<p style='text-align:center;'>Generated by student_performance_tracker</p>\n</body></html>"
    return html


def save_text(path, content):
    """Menyimpan teks ke file (md/html), otomatis buat folder jika belum ada"""
    folder = os.path.dirname(path)
    if folder and not os.path.exists(folder):
        os.makedirs(folder)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
